include classpath("application.conf")

queues {
  capsule-unlock-queue {
    defaultVisibilityTimeout = 10 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

node-address {
  protocol = http
  host = localhost
  port = 9324
  context-path = ""
}
